# Generated by Django 5.0.6 on 2024-06-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcyberuser',
            name='fees',
            field=models.IntegerField(default=0),
        ),
    ]
